### ISSUE TITLE
hl-todo causes long fontification times

### ISSUE THREAD

**Issue by gracjan** [tarsius/hl-todo#14]
`hl-todo` causes large areas of a buffer to be propertized at every keystroke. This gets in the way of usual font-lock optimizations and makes some modes unusably slow, for example `haskell-mode` has rather involved character property rules.

Related issue: https://github.com/haskell/haskell-mode/issues/1360, https://github.com/syl20bnr/spacemacs/issues/6782

**Comment by gracjan** [comment]
Emacs docs say:

> where MATCHER can be either [...] the function name to call to make the search (called with one argument, the limit of the search;

You need to respect search limit in https://github.com/tarsius/hl-todo/blob/master/hl-todo.el#L102

Thanks.

**Comment by tarsius** [comment]
> Emacs docs say:

Where did you find that? I would like to look at the surrounding text.

**Comment by tarsius** [comment]
Thanks @gracjan!
