### ISSUE TITLE
command hl-todo-next should ignore the buffer bounds

### ISSUE THREAD

**Issue by stardiviner** [tarsius/hl-todo#16]
I think command `hl-todo-next` should ignore the buffer bounds, not just fail when reach the buffer end. It should also search before the point.

**Comment by tarsius** [comment]
> I think command `hl-todo-next` should ignore the buffer bounds, 

What do you mean by "ignore"? Wrap around to the beginning of the buffer? I don't think it should do that, that's not how such commands usually work.

> not just fail when reach the buffer end. It should also search before the point.

It doesn't "fail". It detects this situations and forgoes trying to move forward. I suppose it shouldn't do so silently and let the user know what's going on using `user-error`, like other such commands do.
