### ISSUE TITLE
Error when entering shell script editing mode

### ISSUE THREAD

**Issue by Alexander-Shukaev** [tarsius/hl-todo#17]
```
(setq-default hl-todo-activate-in-modes '(fundamental-mode
                                          prog-mode
                                          text-mode))
(add-hook 'after-init-hook #'global-hl-todo-mode))
```

Open a shell script (e. g. `*.sh`) in the `sh-mode` mode and receive the

```
Error in post-command-hook (global-hl-todo-mode-check-buffers): (wrong-type-argument listp bold)
```

error.

**Comment by tarsius** [comment]
I cannot reproduce this. It might be an issue with the theme your are using. A backtrace might help narrowing the issue down.

**Comment by Alexander-Shukaev** [comment]
How to get that backtrace when `(setq-default debug-on-error t)` does not kick in for this error?

**Comment by tarsius** [comment]
You probably can't. Since the error involves the symbol `bold`, I think that is quite likely that it has something to do with a face. So try without your theme and any local face customization.

**Comment by Alexander-Shukaev** [comment]
Kind apologies for the delay, will look into this as soon as time permits.

**Comment by Alexander-Shukaev** [comment]
So far, I was able to narrow it down to the following...  The minimal faulty file is:

```
#!/usr/bin/env sh
'\033[1m'
```

And then, both `global-hl-todo-mode` and `rainbow-mode` should be active.  That is the issue has nothing to do with a theme in the first place.  It is rather some interoperability issue between these two packages.  Any ideas?

**Comment by tarsius** [comment]
> Any ideas?

No, and I still cannot reproduce. Could you please provide step by step reproduction instructions beginning with `emacs -Q`.

**Comment by Alexander-Shukaev** [comment]
I thought it was clear which steps to take in order to reproduce.  Anyway, here goes the recipe:

```
emacs -Q --eval '(add-to-list '"'"'load-path (concat user-emacs-directory "elpa/hl-todo-20170621.1257"))' --eval '(add-to-list '"'"'load-path (concat user-emacs-directory "elpa/rainbow-mode-0.13"))' --eval '(require '"'"'hl-todo)' --eval '(require '"'"'rainbow-mode)'
```

then just open a file with

```
#!/usr/bin/env sh
'\033[1m'
```

contents and issue `M-x rainbow-mode` followed by `M-x hl-todo-mode` and enjoy the `wrong-type-argument listp bold` error.

**Comment by tarsius** [comment]
Okay, I can reproduce this now. However I think `hl-todo` is only incidental to this issue.

After adding these debug statements:

```diff
diff --git a/rainbow-mode.el b/rainbow-mode.el
index ddd9a94..4ac0fbe 100644
--- a/rainbow-mode.el
+++ b/rainbow-mode.el
@@ -1073,6 +1073,9 @@ (defun rainbow-colorize-ansi ()
                              0
                              (if xterm-color? 'face 'font-lock-face)
                              applied)))
+       (message "string:        %S" string)
+       (message "replaced:      %S" replaced)
+       (message "face-property: %S" face-property)
         (unless (listp (car face-property))
           (setq face-property (list face-property)))
         (setq color (funcall (if xterm-color? 'cadr 'cdr)
```

every call to `rainbow-colorize-ansi` gives me:

```
string:        "\\033[1m"
replaced:      #("[1mx" 4 5 (font-lock-face bold))
face-property: bold
Error during redisplay: (jit-lock-function 1) signaled (wrong-type-argument listp bold)
```

`rainbow` expects a list in place where it gets a string. Furthermore it itself put that symbol there (by calling `ansi-color-apply`). So this is a bug in `rainbow-colorize-ansi`, or maybe `ansi-color-apply`.

The reason that `hl-todo-mode` appear to be related to this issue is that turning on causes `font-lock-flush` to be called, which causes `rainbow-colorize-ansi` to be called. Normally `font-lock` runs in a context where errors are suppressed (except for that `Error during redisplay: ...` in the message buffer), that is why you only saw that error when `hl-todo` triggered a `font-lock` flush outside of such a context.

**Comment by tarsius** [comment]
> Furthermore it itself put that symbol there (by calling `ansi-color-apply`). 

Actually that *might* not be true (I kinda overlooked the `applied` variable).

**Comment by Alexander-Shukaev** [comment]
Thanks a lot for the deep analysis, Jonas.  I've just reported it privately to Julien and I will post an update when it is fixed here anyway, just in case anybody in future experiences the same problem.

**Comment by Alexander-Shukaev** [comment]
Pinging @jd.

**Comment by tarsius** [comment]
You are welcome.
