### ISSUE TITLE
How to enable hl-todo in fundamental-mode, like editing text file?

### ISSUE THREAD

**Issue by tddsg** [tarsius/hl-todo#18]
Hi,

I have seen only the keywords TODO, FIXME highlighted in comments in some prog modes like cc-mode, tuareg so far.

Hence, I'd like to ask if it is possible to enable hl-todo when editing text file (*.txt) ?
Currently, I don't know how to do it. Could you please provide some hints?

Thank you very much!

**Comment by tarsius** [comment]
You have to customize `hl-todo-activate-in-modes`.

**Comment by tddsg** [comment]
Hello,
I have tried to customize with `org-mode`, below is the configuration in my Emacs init file. But it seems that the the keywords are not highlighted in org-mode. For example, there isn't any effect when I type `OKAY`, `HACK`:

```
'(hl-todo-activate-in-modes (quote (emacs-lisp-mode text-mode org-mode)))
'(hl-todo-keyword-faces
     (quote
      (("HOLD" . "red")
       ("TODO" . "red")
       ("NEXT" . "red")
       ("OKAY" . "red")
       ("DONT" . "red")
       ("FAIL" . "red")
       ("DONE" . "red")
       ("NOTE" . "red")
       ("HACK" . "red")
       ("FIXME" . "red")
       ("XXX" . "red")
       ("XXXX" . "red")
       ("???" . "red")
       ("BUG" . "red")
       ("OK" . "red"))))
```

**Comment by tarsius** [comment]
This package is only supposed to highlight such keywords in comments in strings. So it probably is only useful for programming modes.
