### ISSUE TITLE
`global-hl-todo-mode` doesn't seem to work

### ISSUE THREAD

**Issue by cmacrae** [tarsius/hl-todo#19]
Hey @tarsius - love this simple little package, very handy 👍 

I use the following configuration with `use-package`:  
```emacs-lisp
(use-package hl-todo
  :init
  (global-hl-todo-mode))
```
It doesn't seem `global-hl-todo-mode` is actually affecting the faces in my buffers.  
I can see that the mode is in fact active, but `TODO`s,`FIXME`s, etc just look normal.  

When I then invoke `hl-todo-mode` it instantly works.  
Any ideas?

**Comment by tarsius** [comment]
The buffer-local mode `hl-todo-mode` is only activated in buffers whose major-mode is one of the modes listed in `hl-todo-activate-in-modes`. By default that's only `emacs-lisp-mode`. That's a bad default and I just changed it. Now `hl-todo-mode` is activated in all buffers whose major-mode derive from `prog-mode`.

**Comment by cmacrae** [comment]
Excellent, thanks for such a quick turn-around on this!

**Comment by c02y** [comment]
Hi, IMHO, `global-hl-todo-mode` should works for any modes like org-mode, prog-mode, text-mode or other buffers of configuration for linux tools like tmux or git, I mean any mode.

But after setting `(global-hl-todo-mode)` in my init.el, and inside those buffers such as configuration files of linux tools, I checked `global-hl-todo-mode` is already `t`, but the keywords like `TODO` or `NOTE` is not highlighted.

Seriously, why would a highlight-todo-keywords package care about what the mode I'm in, why would it have to be one of `prog-mode` or `hl-todo-activate-in-modes`, I'm OK with it if this is for `hl-todo-mode`, but what is the meaning `global-hl-todo-mode`? How can I use `global-hl-todo-mode` to highlight todo keywords in any mode?
