### ISSUE TITLE
Wishlist: an hl-todo-prog-mode

### ISSUE THREAD

**Issue by purcell** [tarsius/hl-todo#2]
Most of my TODOs find themselves in either an `org-mode` buffer or in source code comments. `org-mode` already highlights TODO keywords robustly, and it's a pain to exclude `org-mode` when using `global-hl-todo-mode`.  So a `-prog-mode` variant would be useful.

**Comment by tarsius** [comment]
Implemented in 4af39b24cdd03f7f3612b8d3ae0712270fce4598. I just changed the behavior of the existing mode instead of adding a "prog" variant.
