### ISSUE TITLE
Font-lock TODO: instead of just TODO

### ISSUE THREAD

**Issue by bbatsov** [tarsius/hl-todo#24]
I was wondering if you'd be open to change the font-locking to affect both the "keyword" and the ":" that typically follows it. Many people follow conventions like https://relishapp.com/womply/ruby-style-guide/docs/comments/annotations or https://github.com/bbatsov/ruby-style-guide#comment-annotations and it's a bit annoying the ":" currently retains the comment-face colour. 

Seems like a pretty trivial change that's unlikely to upset someone, but ultimately that's up to you. :-)

Thanks for the great package! (I finally killed some custom code dealing with the same problem in my own config a few days ago)

**Comment by tarsius** [comment]
> Seems like a pretty trivial change that's unlikely to upset someone

Yeah well, I don't really think that looks better, but *after* some other refactoring it was trivial to add an option for this. :stuck_out_tongue_winking_eye:

**Comment by tarsius** [comment]
Uh wait something seems wrong...

**Comment by bbatsov** [comment]
Thanks! Much appreciated!

> I don't really think that looks better

But I do. 😉
