### ISSUE TITLE
FYI: magit-todos

### ISSUE THREAD

**Issue by alphapapa** [tarsius/hl-todo#25]
Hi Jonas,

Forgive the noise, I know you're busy, but I wanted to share this with you:

https://github.com/alphapapa/magit-todos

It's my first magit-related package, and I have to say, what a pleasure it is to use the magit-section tools!  And `hl-todo` is pretty cool, too.  :)

Thanks for all your contributions to Emacsland.

**Comment by tarsius** [comment]
Cheers!
It's always nice to see little extensions like this.

It's pretty funny to see someone bridge two of one's own packages that one didn't really consider to be related. But it makes sense and I might end up using it. It's a bit heavy on the dependencies.
