### ISSUE TITLE
Not working in python-mode?

### ISSUE THREAD

**Issue by wavexx** [tarsius/hl-todo#27]
I'm using emacs 27 from git so I could be an outlier, but I noticed today that hl-todo doesn't seem to find any hit in python-mode's comments.

**Comment by tarsius** [comment]
I can't see a reason why this wouldn't work in `python-mode`. Maybe this is just an instance of #26.

**Comment by wavexx** [comment]
On Mon, Jul 09 2018, Jonas Bernoulli wrote:
> I can't see a reason why this wouldn't work in python-mode. Maybe this is just
> an instance of #26.

It doesn't look like. My guess was some quirk in the syntax-table, but I
didn't have time to debug yet.

Out of curiosity, can you reproduce that? A simple python buffer with

  # TODO:

should do.

**Comment by wavexx** [comment]
Mmh, no. After further testing, with a plain emacs -q it works :/
I guess something is wrong on my side.

**Comment by wavexx** [comment]
Ok, I actually found what the issue is.

**Comment by wavexx** [comment]
```lisp
(setq hl-todo-highlight-punctuation ":"
      hl-todo-keyword-faces '(("TODO" . "#000000)))
````

Doesn't work correctly in python-mode. With the sample file:

````python
# TEST: me
````

You can see that ":" is not highlighted. Previously I had "TODO:" as a keyword (with the colon directly in the name). The issue here is indeed related to the syntax table of python-mode.

In the keyword regexp, "\_>" doesn't match correctly *after* the colon. I recommend moving the anchor "\_>" just after the keyword block to avoid this issue:

````lisp
(concat "\\(\\_<" (regexp-opt (mapcar #'car hl-todo-keyword-faces) t) "\\_>"
                (and (not (equal hl-todo-highlight-punctuation ""))
                     (concat "[" hl-todo-highlight-punctuation "]?"))
                "\\)[[({:;.,?!]?"))
````
