### ISSUE TITLE
Highlighting regression

### ISSUE THREAD

**Issue by bbatsov** [tarsius/hl-todo#30]
See:

![image](https://user-images.githubusercontent.com/103882/46918392-00e6af00-cfd2-11e8-9197-9db6002b3b69.png)

That's my config:

```
(use-package hl-todo
  :ensure t
  :config
  (setq hl-todo-highlight-punctuation ":")
  (global-hl-todo-mode))
```

**Comment by tarsius** [comment]
I can't reproduce that.

**Comment by bbatsov** [comment]
Happens for me all the time. My exact setup is here https://github.com/bbatsov/emacs.d (if you'd like to try with it).

**Comment by bbatsov** [comment]
Hmm, seems it's specific to Clojure mode. But I'm pretty certain this used to work in Clojure mode just fine.

**Comment by bbatsov** [comment]
![image](https://user-images.githubusercontent.com/103882/46920336-00a7dd00-cfed-11e8-8b63-7259938264d5.png)

It's `symbol`.

**Comment by tarsius** [comment]
As in `emacs-lisp-mode`. Must be something else then.

`hl-todo-next`, which uses the same regexp, is able to find `TODO:`.

**Comment by tarsius** [comment]
Still it has something to do with syntax, specifically this: `(("+-*/.<>=!?$%_&:" . "w"))` in `clojure-font-lock-setup`. Removing that fixes things. By the way, I think the `nil` on the next line is a bogus member of SYNTAX-ALIST.

**Comment by tarsius** [comment]
Well the issue was what I though it was, except that I had know idea that some major-modes had a font-lock syntax table that is different from the major-mode syntax-table.

**Comment by bbatsov** [comment]
Thanks! 

Maybe we've messed something up in `clojure-mode`. There's a lot of legacy there that I never got to cleaning up.

**Comment by tarsius** [comment]
And some low-hanging fruit:

```
Compiling /home/jonas/.emacs.d/lib/clojure-mode/clojure-mode.el...

In toplevel form:
clojure-mode.el:476:1:Warning: Unused lexical argument ‘args’
clojure-mode.el:476:1:Warning: Unused lexical argument ‘orig-fun’

In clojure--replace-let-bindings-and-indent:
clojure-mode.el:487:12:Warning: looking-back called with 1 argument, but
    requires 2-3
clojure-mode.el:2023:1:Warning: Unused lexical variable
    ‘clojure-comment-start’
clojure-mode.el:2083:1:Warning: Unused lexical variable ‘beg’

In clojure-cycle-not:
clojure-mode.el:2426:10:Warning: looking-back called with 1 argument, but
    requires 2-3
clojure-mode.el:2640:1:Warning: Unused lexical variable ‘k’
```

:stuck_out_tongue_winking_eye: 

`looking-back called with 1 argument, but requires 2-3` at least must be fixed.

**Comment by tarsius** [comment]
> Maybe we've messed something up in `clojure-mode`.

Doesn't matter there will be other modes that need their syntax-table shadowed. I *think* `with-syntax-table` isn't to expensive. I followed the c code along and it seems fairly harmless.
