### ISSUE TITLE
[Enhancement] Not highlighting in minibuffer

### ISSUE THREAD

**Issue by seagle0128** [tarsius/hl-todo#31]
This is a great package. Thanks for the great work!
A minor suggestion: should not highlight in minibuffer like this.

![image](https://user-images.githubusercontent.com/140797/48298439-6dcd6600-e4f8-11e8-8ad4-07cf9d9d0889.png)

**Comment by tarsius** [comment]
It shouldn't do that because the minibuffer normally doesn't use a mode deriving from one of the modes listed in `hl-todo-activate-in-modes`. Please investigate why this is different for you.

**Comment by seagle0128** [comment]
Hmm.. It works fine with bare emacs. Should be configuration issue. Closing it.
Thanks for confirmation.
