### ISSUE TITLE
Make option for hl-todo-highlight-punctuation to be highlighted before keyword too

### ISSUE THREAD

**Issue by JSpenced** [tarsius/hl-todo#34]
I added this to hl-todo.el to modify the setting of the regexp to include hl-todo-highlight-punctuation before the keyword-faces as well as after. I figure add a variable  `hl-todo-highlight-punctuation-before nil` and if set to `t` then do as below.

I can write a PR if necessary so let me know. Figured this is easy enough and don't know much about writing defcustoms was the only reason I didn't already.

```
(defun hl-todo--setup ()
  (setq hl-todo--regexp
	(concat "\\("
		(and (not (equal hl-todo-highlight-punctuation ""))
		     (concat "[" hl-todo-highlight-punctuation "]*"))
		"\\<"
		(regexp-opt (mapcar #'car hl-todo-keyword-faces) t)
		"\\>"
		(and (not (equal hl-todo-highlight-punctuation ""))
		     (concat "[" hl-todo-highlight-punctuation "]*"))
		"\\)"))
  (setq hl-todo--keywords
        `(((lambda (bound) (hl-todo--search nil bound))
           (1 (hl-todo--get-face) t t))))
  (font-lock-add-keywords nil hl-todo--keywords t))
```

**Comment by tarsius** [comment]
Why would you want that? Seems strange to me, why would you write e.g. ?TODO instead of TODO? Maybe if you provide an example I will reconsider, but its more likely that you will have to redefine this function in your configuration.

**Comment by JSpenced** [comment]
Yeah, I think for a question mark that I agree with you. I often write :TODO: or :FIX:, so this is why it was desired. I guess I can just get used to writing TODO: but the other package I was using in a different editor I got used to writing it this way.

**Comment by tarsius** [comment]
Is there some convention to place colons around todo keywords? Maybe the documentation of one of those other packages links to some relevant information?

**Comment by JSpenced** [comment]
I will try to find the relevant documentation and post it here.

**Comment by tarsius** [comment]
I am considering what you did in the code above. I.e. not add a new option, and deal with that when and if someone else is bothered by such a change.

**Comment by JSpenced** [comment]
Yeah, that seems reasonable to me. I can't imagine since it is usually in comment strings that it should make anyone's setup worse. If they were doing that and it wasn't highlighting before this should only improve it.

**Comment by tarsius** [comment]
I have experimented with this a bit.

With the default settings the `TODO` in `:TODO:` is highlighted. With `(setq hl-todo-highlight-punctuation ":")` only the second `:` is additionally highlighted, which looks weird. However the look I definitely like the best is the default: `TODO` is highlighted, but the `:`s around it are not. So I don't think I will make `hl-todo-highlight-punctuation` affect preceding punctuation also and recommend that you just reset `hl-todo-highlight-punctuation` to its default value.

**Comment by JSpenced** [comment]
Okay, I understand. Yeah since I am not currently using that notating. I just have it in some old files. I like that it highlights `TODO:` so I will keep it. I do like that you changed it to allow regex in the `todo-keyword-faces` as I think that is better.
