### ISSUE TITLE
Can't seem to get regex to recognize question marks ?

### ISSUE THREAD

**Issue by JSpenced** [tarsius/hl-todo#35]
No matter what I do. I can't seem to get ??? to highlight properly.
This is what is set by my `hl-todo-keyword-faces` as the `regexp`:
```
"\\([-:*/~=#<>|\\]*\\<\\(\\?\\?\\?\\??\\|DONT\\|F\\(?:AIL\\|I\\(?:NISHED\\|XME\\)\\)\\|H\\(?:ACK\\|OLD\\)\\|KLUDGE\\|NOTE\\|OKAY\\|PROG\\|T\\(?:0\\(?:[0D]0\\)\\|EMP\\|HEM\\|OD\\(?:0\\|OO\\)\\)\\|UNSURE\\|XXXX?\\)\\>[-:*/~=#<>|\\]*\\)"
```
I manually set a default so any buffer even without hl-todo activated can run occur on the keywords. Even using the [?], it still doesn't recognize question marks. Maybe this has something to do with occur because if I search using this regex `\\([?]\\{3,5\\}` it works fine. I think the regex is just handed off to occur.
(setq-default hl-todo--regexp "\\([-:*/~=#<>|\\\\]*\\<\\([?]\\{3,5\\}\\|UNSURE\\|FINISHED\\|DON[ET]\\|F\\(?:AIL\\|IXME\\)\\|H\\(?:ACK\\|OLD\\)\\|KLUDGE\\|N\\(?:EXT\\|OTE\\)\\|OKAY\\|PROG\\|T\\(?:EMP\\|HEM\\|ODO\\|0D0\\)\\|XXXX?\\)\\>[-:*/~=#<>|\\\\]*\\)")

**Comment by JSpenced** [comment]
Was this pushed up to melpa or should I use git?

**Comment by tarsius** [comment]
If it's on `master` then it's on Melpa a few hours later.

**Comment by JSpenced** [comment]
Yeah needed to refrese the package contents. I have a problem that it highlights in the buffer but isn't found in the matches. Do you also have this problem?

![image](https://user-images.githubusercontent.com/43424787/55721419-f9c0bc80-59c8-11e9-8888-73fdaeb71ba4.png)

**Comment by tarsius** [comment]
Fixed.

**Comment by tarsius** [comment]
I am afraid `???` is once more not highlighted and I don't have any intention to restore support anytime soon, possibly never. Sorry you will have to live with that.

See 823ca3751e4cac6e936800ddf2f19d6f96eeb422 for the issues caused by supporting `???` again.

**Comment by JSpenced** [comment]
Okay, I have just updated to using QQQ+ instead of using question marks.

**Comment by tarsius** [comment]
A pragmatic choice. :heart:
