### ISSUE TITLE
jit-lock errors

### ISSUE THREAD

**Issue by hmelman** [tarsius/hl-todo#36]
I'm seeing a lot of these errors when opening a file when `global-hl-todo-mode` is enabled. An error isn't signaled but the file is marked modified as soon as it's opened and several of these errors are in  the *messages* buffer. I believe this is recent and suspect it has to do with the new keyword regexp support.

    Error during redisplay: (jit-lock-function 4429) signaled (error Lisp nesting exceeds max-lisp-eval-depth)

**Comment by tarsius** [comment]
Pushed https://github.com/tarsius/hl-todo/commit/b26423b07293d7e47d28544ce0a4c9a76e5d3a6f, which should fix this. While https://github.com/tarsius/hl-todo/commit/396d0923602a855fca58f43c98832afb66a479fa triggered this issue, it isn't really to be blamed. It just happened to push the depth over the edge for many files. The recursive approach added in https://github.com/tarsius/hl-todo/commit/cdc22667f4c7dc3781390c7f9dc8fe2f2c325147 ultimately caused this.

**Comment by hmelman** [comment]
Now emacs hangs when opening a file with `global-hl-todo-mode` enabled.

**Comment by tarsius** [comment]
See https://github.com/syl20bnr/spacemacs/issues/12143#issuecomment-481711416, that should fix it.

**Comment by hmelman** [comment]
Yes that seems to have fixed it. FWIW I don't and have never used spacemacs or a theme, but I did have `("???" . "#cc9393")` as the last entry in my `hl-todo-keyword-faces`. I had customized the default value, probably long enough ago that `hl-todo` included it in the default value.

It might be worth code to scan `hl-todo-keyword-faces` for a `"???"` value to give a warning and to remove it.

**Comment by tarsius** [comment]
> It might be worth code to scan hl-todo-keyword-faces for a "???" value to give a warning and to remove it.

I already added code to remove it. No warning though.
