### ISSUE TITLE
Longest keyword no longer selected

### ISSUE THREAD

**Issue by bcc32** [tarsius/hl-todo#40]
With `hl-todo-keyword-faces` set to:

```lisp
  (setq hl-todo-keyword-faces
	'(("TODO" . "#ff0000")
	  ("TODO-soon" . "#ffff00")))
```

Instances of `TODO-soon` in the buffer are highlighted incorrectly---only the `TODO` part is highlighted, in red rather than yellow.

**Comment by bcc32** [comment]
By the way, this is due to Emacs regexp alternation (`|`) picking the first match instead of the longest match (as POSIX does).  It's probably also fine if this new behavior is kept, but it'd be good to document it somewhere in that case.

**Comment by tarsius** [comment]
Thanks for the report!

**Comment by bcc32** [comment]
Great, thanks!
