### ISSUE TITLE
how can hl-todo-occur make use of helm

### ISSUE THREAD

**Issue by c02y** [tarsius/hl-todo#44]
Currently `hl-todo-occur` will create a new buffer contains all the todo keywords and lines in the buffer.

It is great if it can make use of helm, like `hl-todo-insert`

**Comment by tarsius** [comment]
`hl-todo-insert` does not explicitly use `helm`. It uses `completing-read` and `helm-mode` changes how that function behaves.

`hl-todo-occur` does not use completion, so turning `helm-mode` does not change its behavior. I am guessing that a `helm-occur` command exists somewhere. Look at the definition of that and of `hl-todo-occur`. That might be enough to figure out how to write `helm-hl-todo-occur`.

**Comment by c02y** [comment]
I foud related issue https://github.com/emacs-helm/helm/issues/1834 , left a comment there.

**Comment by tarsius** [comment]
> I foud related issue emacs-helm/helm#1834 , left a comment there.

There's a suggestion for you there. You'll have to help us help you.

I am closing this issue because I don't think `hl-todo` is to blame.
