### ISSUE TITLE
hl-todo-mode will affect magit-diff highlights

### ISSUE THREAD

**Issue by c02y** [tarsius/hl-todo#45]
Just like I posted on https://github.com/tarsius/hl-todo/issues/19#issuecomment-501569924

Since global-hl-todo-mode is not actually global, so I use 
~~~
 (define-globalized-minor-mode my-global-hl-todo-mode hl-todo-mode
    (lambda () (hl-todo-mode 1)))
  (my-global-hl-todo-mode 1)
~~~
to make hl-todo-mode as global mode as it should be.

But I found out that when I use it, it will disable highlights in magit-diff, there are no highlights in magit-diff at all.

**Comment by tarsius** [comment]
That's because you made it more global than it should be.

`hl-todo-mode` relies on font-lock, which can be an issue in buffers that do not use font-lock. In the case of Magit this could be fixed with https://github.com/magit/magit/pull/3886. It won't "fix" other incompatible modes though.

**Comment by c02y** [comment]
OK. So hl-todo-mode shouldn't/couldn't be global mode like other global-modes?

**Comment by tarsius** [comment]
I would argue so but its not unreasonable to disagree. Anyway I will have another look at that pr and probably merge it.

**Comment by tarsius** [comment]
I only ever intended `hl-todo-mode` to be used in file-visiting buffers, but obviously todo keywords can also appear in other buffers and it might be useful to highlight them there too. But IMO those modes should be explicitly included instead of turning on `hl-todo-mode` everywhere. In the case of Magit neither approach works until I have merged that pr.

**Comment by c02y** [comment]
There are so many different kinds of files/buffers, IMO, explicitly including every one of them is not recommended.

Maybe we can enable `hl-todo-mode` everywhere like other normal global-modes, but providing an variable that explicitly excludes some modes such magit.

For example, I tweak the snippet a little bit to exclude magit-mode:
~~~
  (define-globalized-minor-mode my-global-hl-todo-mode hl-todo-mode
    (lambda ()
      (when (not (derived-mode-p 'magit-mode))
        (hl-todo-mode 1))))
  (my-global-hl-todo-mode 1)

~~~

Now  `my-global-hl-todo-mode` works well for all modes except magit-mode.

Of course, you can provide an exclude-related variable for us in hl-todo package.
Or maybe you got better solution.

**Comment by c02y** [comment]
Since I want real global-hl-todo-mode + hl-todo-exclude-modes (for magit-mode) variable, the latest release only add hl-todo-exclude-modes and hl-todo-include-modes, and I have no real global-hl-todo-mode, and have to add modes using hl-todo-include-modes. Anyway, maybe this is what other people want.

So after updating the hl-todo package
~~~
 (define-globalized-minor-mode my-global-hl-todo-mode hl-todo-mode
    (lambda ()
      (when (not (derived-mode-p 'magit-mode))
        (hl-todo-mode 1))))
  (my-global-hl-todo-mode 1)
~~~
is still the config I should use. Nothing changes.

**Comment by tarsius** [comment]
I disagree with your classification of `global-hl-todo-mode` as "not a real global mode".

*Major-modes* are supposed to drive from some more basic major-mode. That way they are classified into categories. Some basic categories are `prog-mode`, `text-mode`, `special-mode` and `fundamental-mode`. If you add the latter two to `hl-todo-include-modes`, then you get almost what you consider a "real global mode". The only exceptions are some major-modes that need fixing.

**Comment by c02y** [comment]
OK, maybe I have some misunderstanding of `global-x-mode`. 

Anyway, I'll just use that code snippet of config to get what I want. Thanks for your support.
