### ISSUE TITLE
hl-todo-insert double comment sign

### ISSUE THREAD

**Issue by thorstengrothe** [tarsius/hl-todo#48]
Just a simple question. When I run `hl-todo-insert` it inserts something like this

`; TODO`

but I want two comment signs depending on the language I use like so:

`;; TODO`

how can I do this?

Regards
Thorsten

**Comment by tarsius** [comment]
What language would that be? A lisp? Is it `;;` at the beginning of line but `;` elsewhere?

(Look at the code for why I am asking these questions.)

**Comment by thorstengrothe** [comment]
Yes you are right, the only reason for this is `aggressive-indent-mode` which I configured to indent comments too. So if a `;TODO` stands at the beginning of a line it get's badly indented. If we have too `;;` it does not happen. Of course I can write my TODOS at the end of each line, this works fine...
