### ISSUE TITLE
Don't highlight punctuation.

### ISSUE THREAD

**Issue by jcs090218** [tarsius/hl-todo#49]
Is there an option so when I set `hl-todo-highlight-punctuation` but I don't want the punctuation to be highlighted. Thanks!

**Comment by tarsius** [comment]
*Not* setting `hl-todo-highlight-punctuation` might do the trick. If it doesn't, then you'll have to give examples. What mode? What text?

**Comment by tarsius** [comment]
Did some testing:

```diff
diff --git a/hl-todo.el b/hl-todo.el
index 1fe86eb..145bfbb 100644
--- a/hl-todo.el
+++ b/hl-todo.el
@@ -189,11 +189,20 @@ (defun hl-todo--setup-regexp ()
   (setq hl-todo--regexp
         (concat "\\(\\<"
                 "\\(" (mapconcat #'car hl-todo-keyword-faces "\\|") "\\)"
-                "\\(?:\\>\\|\\>\\?\\)"
+                ;;"\\(?:\\>\\|\\>\\?\\)" ; 1 716ada1a8e3f62fb943b777d4bf5f94e3c613e84
+                ;;"\\(?:\\>\\|\\>?\\)" ; 2 f7d97056d17ef7fc04f4fa0b65a703d1d1a5a6b8
+                "\\>" ;3 before
                 (and (not (equal hl-todo-highlight-punctuation ""))
                      (concat "[" hl-todo-highlight-punctuation "]*"))
                 "\\)")))
 
+;;        TODO TODOa TODOabc TODO. TODO? ???
+;; goal:  ----               ----  ----  ---
+;; 1:     ----               ----        ---
+;; 2:     ---- ----  ----    ----  ----  ---
+;; 3:     ----               ----        ---
+;; okay:  ----               ----  ----
+
 (defun hl-todo--setup ()
   (hl-todo--setup-regexp)
   (setq hl-todo--keywords
```

It might be okay to just give up on highlighting `???` and similar. Don't really see another solution.

**Comment by tarsius** [comment]
I have reverted to before the attempt to highlight `???` again.

While you have never actually said what doesn't work for you I am guessing that you wanted `TODO` in `TODO?` to be highlighted (just like it always was in `TODO.`). That works again now.

**Comment by jcs090218** [comment]
Is okay, I think your solution is the best solution for now. Thanks for replying!
