### ISSUE TITLE
"Note" in comments is highlighted with `nil` as face

### ISSUE THREAD

**Issue by wasamasa** [tarsius/hl-todo#5]
I've read the implementation of [SRFI 113](http://srfi.schemers.org/srfi-113/srfi-113.html) today and noticed that some of its comments contain "Note" which was highlighted with the default face instead of the comment face (since it shouldn't match the "NOTE" regex used to determine todo keywords). Inspecting the word with `M-x describe-char` revealed that it was using a `nil` face which looks like something went wrong during fontification. Perhaps a match did occur, but no suitable face could be found?

**Comment by tarsius** [comment]
Funny, just yesterday I was thinking NOTE should be highlighted too. I did so by adding an entry to the default value of `hl-todo-keyword-faces`. But I am not going to add everything there that some user would want, you can also customize that variable. If you modify it manually, then you have to call `hl-todo-set-regexp` after doing so.

**Comment by wasamasa** [comment]
This is not about adding a keyword, I've just pointed out some curious behaviour for my customization of hl-todo-mode you can see in my [init.org](https://github.com/wasamasa/dotemacs/blob/master/init.org#hl-todo). I've set the RE appropriately, but instead of using color strings went for the hl-todo face. Doing so yields the behaviour I've described.

**Comment by tarsius** [comment]
Ah sorry, did not read properly. There was a bug in `1.4.1` (I removed the `hl-todo` face!). Once you have updated to `1.4.2` it should work again. And then you should also only modify `hl-todo-keyword-faces` manually, and the call `magit-todo-set-regexp` (that's a recent addition).

**Comment by wasamasa** [comment]
I've updated again, did change my customization to the recommended format and still experience the behaviour. Using `M-x hl-todo-mode` again to disable it undoes the anomaly, re-enabling it introduces it. I'll investigate further into how exactly fontification of it works and see whether I can dig up more.

Attempting to reproduce the same in the scratch buffer failed, for some reason it needs to be a file you've loaded from disk, not a new document you just started writing.

**Comment by wasamasa** [comment]
I've noticed that using `M-: (re-search-forward hl-todo-regexp nil t)` on the sample code does indeed jump ahead of the anomaly, looking it up with `(hl-todo-get-face)` afterwards did return `nil`.  Let-binding `case-fold-search` as demonstrated next fixes it for me.

```elisp
(defvar hl-todo-keywords
  `(((lambda (_)
       (let (case-fold-search)
         (and (re-search-forward hl-todo-regexp nil t)
              (nth 8 (syntax-ppss))))) ; inside comment or string
     (1 (hl-todo-get-face) t))))
```

PS: You probably meant to write `hl-todo-set-regexp` in your last post.

**Comment by wasamasa** [comment]
```
File mode specification error: (error "No match 1 in highlight (1 (hl-todo-get-face) t)")
Error during redisplay: (jit-lock-function 528) signaled (error "No match 1 in highlight (1 (hl-todo-get-face) t)")
```

Shall I open a pull request with my proposed fix?
