### ISSUE TITLE
I have to enable `hl-todo-mode` in LaTeX-mode-hook?

### ISSUE THREAD

**Issue by avatar-lavventura** [tarsius/hl-todo#52]
Currenty I am on `LaTeX-mode-hook` and added following line `global-hl-todo-mode` into `.emacs` file to use [hl-todo][1]. On its readme it says:

> To highlight keywords turn on `hl-todo-mode` in individual buffers or use the the global variant `global-hl-todo-mode`.

My setup:
```
; L A T E X ;
(setq LaTeX-item-indent 0)
(add-hook 'LaTeX-mode-hook 'turn-on-auto-fill)
(setq-default fill-column 80)  ; M-q
(require 'tex)

(add-hook 'LaTeX-mode-hook (lambda ()
  (TeX-global-PDF-mode t)
  (global-hl-todo-mode t)  ; <= added here
  ))

(global-hl-todo-mode 1) ; <= added bottom of the page
```

----

When I open `emacs -nw file.tex`, I need to disable and than re-enable `global-hl-todo-mode` in order to use it. Is there any way to fix this issue? 

Please note that, this was working perfectly fine in `python-mode`.

  [1]: https://github.com/tarsius/hl-todo
  [2]: https://emacs.stackexchange.com/a/24971/18414

**Comment by tarsius** [comment]
> `LaTeX-mode-hook`

I don't think that actually exists. `LaTeX-mode` is an alias for `latex-mode`, but as far as I can tell the same isn't true for the hook variable.

On a mode hook you should enable `hl-todo-mode` not `global-hl-todo-mode`.

But just enabling `global-hl-todo-mode` directly at the top-level of the init file should be enough anyway. For me that works.

**Comment by avatar-lavventura** [comment]
Sorry yes I was using `latex-mode`.

I have added `(global-hl-todo-mode 1)` to top of the `.emacs` file. And also added:
`(add-hook 'LaTeX-mode-hook 'hl-todo-mode)`.

I observer that I have to do `M-x` hl-todo-mode (disables) and than `M-x hl-todo-mode to re-enable again to make it work.

**Comment by tarsius** [comment]
Make sure you are using the latest `hl-todo` version.

```lisp
(add-hook 'LaTeX-mode-hook 'hl-todo-mode)
           ^^^^^
           Again, I don't think that has any effect.
           Try `latex-mode-hook'.
```

**Comment by tarsius** [comment]
I recommend you try to reproduce this issue starting from `emacs -Q`. All you should need to do is to then interactively enabling `global-hl-todo-mode`. After that `hl-todo-mode` should be automatically enabled and effective in `latex-mode` buffers (and others).

If that works then start adding your configuration piece by piece until you hit the thing that causes the breakage.

**Comment by avatar-lavventura** [comment]
Both version are same on `linux` and `mac`

`Linux: 20200103.1239` | `Mac:   20200103.1239`

It works when I open an empty file and type `TODO`. It does working on the `.tex` file I was working on it. When I copy that file under a different name it works. There were other files with different endings maybe they affect the output.

```
$ emacs -nw Paper.tex  // does not work
$ cp Paper.tex Paper1.tex && emacs -nw Paper1.tex // works

$ ls
Paper.aux         Paper.log
Paper.bbl          Paper.out
Paper.blg          Paper.pdf
Paper.fdb_latexmk  Paper.tex
Paper.fls          Paper.txt
```

**Comment by tarsius** [comment]
```
$ emacs -nw Paper.tex  // does not work
$ cp Paper.tex Paper1.tex && emacs -nw Paper1.tex // works
```

Well that is weird. I don't see how `hl-todo` itself could be responsible for that difference.

Check if the same major-mode gets enabled in both buffers. That's all I got.

**Comment by avatar-lavventura** [comment]
@tarsius: I have this follow up maybe it might solve my issue:

https://emacs.stackexchange.com/a/58769/18414

**Comment by tarsius** [comment]
For some reason as soon as I followed the link this rang a bell.

This issue came up before in https://github.com/tarsius/hl-todo/issues/26. Later I'll read through that again and maybe add a FAQ entry.

**Comment by avatar-lavventura** [comment]
Adding: `(add-hook 'TeX-update-style-hook 'hl-todo-mode)` solved my problem.

**Comment by tarsius** [comment]
Added https://github.com/tarsius/hl-todo/wiki.
