### ISSUE TITLE
there is no color in DEBUG,GOTCHA and so on

### ISSUE THREAD

**Issue by nesteiner** [tarsius/hl-todo#54]
![2020-06-08 17-14-23 的屏幕截图](https://user-images.githubusercontent.com/46296608/84013492-9145e480-a9ab-11ea-910c-42b3a84efe6a.png)

**Comment by nesteiner** [comment]
I use 'vim-colors theme,I don't know if I have done something wrong

**Comment by tarsius** [comment]
The readme explains how to deal with that. It even uses these two keywords in the example!

**Comment by nesteiner** [comment]
![image](https://user-images.githubusercontent.com/46296608/84106935-04546700-aa4f-11ea-8baf-8c86824954bc.png)
___
still useless
