### ISSUE TITLE
I can't get regexp with colon to work

### ISSUE THREAD

**Issue by magthe** [tarsius/hl-todo#58]
I have `hl-todo-highlight-punctuation` set to its default, `""` and then try to add `todo:` as a keyword using

```
(add-to-list 'hl-todo-keyword-faces
               `("todo:" . ,(alist-get "TODO" hl-todo-keyword-faces
                                        nil nil 'equal)))
```

(Some of my co-workers use other editors and insist on using `todo:` as their keyword. If I add `todo` there's a bit too much that is matched and highlighted so I'd really like to include the colon in the keyword.)

Unfortunately I get no matches at all when using that keyword. I've checked with `re-builder` and the expression `"todo:"` is matching, so why isn't `hl-todo`? Is this expected behaviour?

**Comment by tarsius** [comment]
> If I add `todo` there's a bit too much that is matched and highlighted so I'd really like to include the colon in the keyword.

Doing that anyway is probably a rather reasonable approach anyway.

The larger problem is that this is supposed to work in lots of different context according to lots of different preferences and catering to one particular case has proven to break other cases many times now. So I don't want to touch it anymore.

You can either change the syntax class of `:` (probably don't want that), or you can modify `hl-todo--regexp` and do something about the `\\>`. See #49 for some inspiration.

**Comment by magthe** [comment]
Would something along these lines be accepted as a PR?

```
From 417a97109ac33d24af1868305acead03e4b5bc53 Mon Sep 17 00:00:00 2001
From: Magnus Therning <magnus@therning.org>
Date: Mon, 4 Jan 2021 14:11:24 +0100
Subject: [PATCH] Introduce hl-todo-require-trailing-punctuation

Allow configurations where trailing punctuation is required for a match. Default
it to `nil` to keep original behaviour.
---
 hl-todo.el | 12 +++++++++++-
 1 file changed, 11 insertions(+), 1 deletion(-)

diff --git a/hl-todo.el b/hl-todo.el
index a6456a1..2587a3f 100644
--- a/hl-todo.el
+++ b/hl-todo.el
@@ -172,6 +172,13 @@ including alphanumeric characters, cannot be used here."
   :group 'hl-todo
   :type 'string)
 
+(defcustom hl-todo-require-trailing-punctuation nil
+  "Require trailing punctuation after keywords."
+  :package-version '(hl-todo . "9.9.9")
+  :group 'hl-todo
+  :type 'bolean
+  )
+
 (defvar-local hl-todo--regexp nil)
 (defvar-local hl-todo--keywords nil)
 
@@ -190,7 +197,10 @@ including alphanumeric characters, cannot be used here."
                 "\\(" (mapconcat #'car hl-todo-keyword-faces "\\|") "\\)"
                 "\\>"
                 (and (not (equal hl-todo-highlight-punctuation ""))
-                     (concat "[" hl-todo-highlight-punctuation "]*"))
+                     (concat "[" hl-todo-highlight-punctuation "]"
+                             (if hl-todo-require-trailing-punctuation
+                                 "+"
+                               "*")))
                 "\\)")))
 
 (defun hl-todo--setup ()
-- 
2.30.0

```

**Comment by tarsius** [comment]
Wait... isn't `(setq hl-todo-highlight-punctuation ":")` enough? Seems to work for me.

Sort that also highlights `TODO:::::::::::::::` but you know...

**Comment by magthe** [comment]
It's not enough since it will match and highlight `TODO`. In other words

- I want to match `TODO:`
- I don't want to match `TODO`

**Comment by tarsius** [comment]
Right, I should have understood that before. But I still don't understand why that is such a big deal. Do you worry that you might write `TODO`, see it light up, and forget to also type the `:` that makes it a "proper todo item" according to the projects convenctions?

**Comment by magthe** [comment]
No, I have co-workers insisting on using lowercase rather than uppercase, and I find that adding the key `"todo"` lights up a few too many places (like half the rows in `hl-todo` itself). Since they, and I, _always_ add a `:`, I'd love to have a way to require a trailing punctuation. I hope that makes sense.

Anyway, I'm perfectly fine with just forking `hl-todo` and maintain the change myself.

**Comment by tarsius** [comment]
Okay. PR please! :grin:

Please make a few changes first, seen here:

```elisp
hl-todo-require-punctuation: New option

(defcustom hl-todo-require-punctuation nil
  "Whether to require punctuation after keywords."
  :package-version '(hl-todo . "3.3.0")
  :group 'hl-todo
  :type 'boolean)

(if hl-todo-require-punctuation "+" "*")
```
