### ISSUE TITLE
How to make the highlights re-use the original background color?

### ISSUE THREAD

**Issue by NightMachinary** [tarsius/hl-todo#60]
I have set a custom background color for some of my org-mode tags. This background color gets ignored by my hltodo highlights:

```
(defface special-comment '((t (:inherit t :foreground "#3437eb" :weight bold))) "This is just a doc string")

  (setq 
        hl-todo-keyword-faces
        `(
          ("@[^][[:space:](){};,\n\"=]+" special-comment)
          ))
```
![image](https://user-images.githubusercontent.com/36224762/116875174-bbda0500-ac2f-11eb-8d95-adfcff2e9c46.png)

**Comment by tarsius** [comment]
It's weird it took me so long to do this. It's quite a trivial change.

**Comment by NightMachinary** [comment]
Thanks!
