### ISSUE TITLE
Fontification is slow, use jit-lock instead

### ISSUE THREAD

**Issue by minad** [tarsius/hl-todo#61]
See for example the `bug-reference-prog-mode` which uses `jit-lock-register`.

https://github.com/emacs-mirror/emacs/blob/45d711a356b4c5e75d0b6e4391313ca34f57b4bb/lisp/progmodes/bug-reference.el#L497-L505

https://github.com/emacs-mirror/emacs/blob/45d711a356b4c5e75d0b6e4391313ca34f57b4bb/lisp/progmodes/bug-reference.el#L100-L122

**Comment by minad** [comment]
Do you think that would be an option for hl-todo?

I've also played around with using `font-lock-add-keywords` directly. But then one also gets highlighting in comments and I am not sure if it is possible to avoid this.

~~~ elisp
(defvar my/todo-keywords
  '(("HOLD" . "#d0bf8f")
    ("TODO" . "#cc9393")
    ("NEXT" . "#dca3a3")
    ("THEM" . "#dc8cc3")
    ("PROG" . "#7cb8bb")
    ("OKAY" . "#7cb8bb")
    ("DONT" . "#5f7f5f")
    ("FAIL" . "#8c5353")
    ("DONE" . "#afd8af")
    ("NOTE"   . "#d0bf8f")
    ("KLUDGE" . "#d0bf8f")
    ("HACK"   . "#d0bf8f")
    ("TEMP"   . "#d0bf8f")
    ("FIXME"  . "#cc9393")
    ("XXX+"   . "#cc9393")))

(defun my/todo-fontify ()
  (unless (derived-mode-p 'org-mode)
    (font-lock-add-keywords
     nil
     (mapcar (lambda (x)
               `(,(concat "\\<" (car x) "\\>") 0 '(:weight bold :foreground ,(cdr x)) prepend))
             my/todo-keywords))))

(add-hook 'prog-mode-hook #'my/todo-fontify)
(add-hook 'text-mode-hook #'my/todo-fontify)
~~~

**Comment by tarsius** [comment]
Interesting. I'll have to look into that. I have some other packages that do it like `hl-todo`, and I'll probably look at those first, because they are simpler.

> Fontification is slow,

Just *initial* funtification, right?

**Comment by minad** [comment]
Yes, the startup slowdown bothers me. It is slow when opening large files
