### ISSUE TITLE
How to prevent some TODO words to be colored based on its starting character

### ISSUE THREAD

**Issue by avatar-lavventura** [tarsius/hl-todo#64]
`hl-todo` makes all `TODO` keywords as the color I defined.

Would it be possible to prevent coloring for specific patterns such as the ones have `/` character right before or the ones followed by `"` character?

Ex: ```"/home/user/TODO"```

**Comment by tarsius** [comment]
The regexp (`hl-todo--regexp`) used to find the keywords is `"\\(\\<\\(HOLD\\|TODO\\|...\\)\\>\\)"`. `\\<` and `\\>` mean "word boundary". So to make the `TODO` in `/path/to/TODO` not be highlighted you can change `/` not to cause a word boundary by declaring it a character that can be part of a word:

```elisp
(modify-syntax-entry ?/ "w" hl-todo--syntax-table)
```
