### ISSUE TITLE
hl-todo-occur-directory

### ISSUE THREAD

**Issue by ZelCloud** [tarsius/hl-todo#68]
Would it be possible to add a hl-todo-occur-directory command, so there's an easy way to view a project's TODOs vs going file by file?

**Comment by tarsius** [comment]
Have you tried the `magit-hl-todo` package? That might satisfy your needs. It doesn't do what you requested, but maybe what it does is even more to your liking.

**Comment by ZelCloud** [comment]
Hey @tarsius, I've tried out the ```magit-hl-todo``` package, It's good enough for my needs. Thanks for the recommendation.

Though I think a hl-todo-occur-directory would still be a useful command, since it seems like magit-hl-todo pulls the entire repository's hl items. Which is a lot of extra noise especially for larger repos. 

```Magit-todos-list``` is good enough though, so if ```hl-todo-occur-directory```  is outside of the scope of this package. Feel free to close the issue.

Also for anyone else on windows - I needed to add the following to get magit-todos-list to work:
https://github.com/alphapapa/magit-todos/issues/29
```elisp
;; NOTE: ripgrep (rg) will need to be installed separately 
;; grep and git-grep usage on windows through emacs is a bit spotty with this package.

;; ensure ripgrep is within your emacs path
(let ((mypaths
		 '(
		   "C:/Users/%USERNAME%/dev-tools/ripgrep-13.0.0-x86_64-pc-windows-msvc"
           )
           )))

(setenv "PATH" (mapconcat 'identity mypaths ";"))
(setq exec-path (append mypaths (list "." exec-directory)))

;;;;;;

(use-package magit-todos
  :ensure t
  :defer t
  :config
  ;; nice doesn't exist on windows make sure its not used
  (setq magit-todos-nice nil) 
  )
```

**Comment by tarsius** [comment]
Occur is about finding matches in buffers, not files. There is no `occur-directories` that I could wrap around. Instead I have added a command that wraps `rgrep`.
