### ISSUE TITLE
The `hl-todo-occur` function shows only current buffer

### ISSUE THREAD

**Issue by refaelsh** [tarsius/hl-todo#71]
The `hl-todo-occur` function shows only current buffer todos.
How can I show todos from all the files of my project?

P.S.
Emacs newbie here transitioning from Neovim.

**Comment by tarsius** [comment]
This command uses Emacs' `occur` functionality, which is a single-buffer search feature. Something like `multi-occur` exists, as a third-party package. As far as I know that also only deals with buffers, as opposed to files (which may or may *not* be open in a buffer).

To search files use `hl-todo-rgrep`.

**Comment by refaelsh** [comment]
I understand. Thank you very much.

**Comment by tarsius** [comment]
And welcome :grinning:

**Comment by refaelsh** [comment]
Followup question, please: The 'hl-todo-rgrep' function, when it is called, I have to specify the path where to search. This in turn means pressing RET. Therefore, it is not enough to just bind the 'hl-todo-rgrep' function to some key. What can be done, please?

**Comment by refaelsh** [comment]
I understand. Again, thank you very much :-)
