### ISSUE TITLE
[Feature request] Add support for punctuation in keywords

### ISSUE THREAD

**Issue by o0nd7ots** [tarsius/hl-todo#77]
Right now if one of the elements of my `hl-todo-keyword-faces`is `("DNW!" font-lock-warning-face bold)` and it does not highlight.

I wish that this package could do that. Is this possible to implement?

**Comment by tarsius** [comment]
I've added `hl-todo-highlight-punctuation` in response to a similar request, #24.

The problem is that we match keywords using word boundaries (`"\\<WORD\\>"`) and punctuation characters are never part of words, they inherently appear outside of words.

You can set that variable to `"!"` and add `"DNW"` instead of `"DNW!"` to `hl-todo-keyword-faces`. But that means that `DNW` without the `!`, and `!` after any other keyword, will both be highlighted as well.

**Comment by o0nd7ots** [comment]
I have remade the `hl-todo-highlight-punctuation` to work on a list of strings instead of one string.
I have created a local branch (in Magit) and I do not know what to do next. Can I ask for help @tarsius?

**Comment by tarsius** [comment]
> I have remade the `hl-todo-highlight-punctuation` to work on a list of strings instead of one string. I have tested it and it works fine, so I want to share it with everybody.

I disagree that this is objectively better. Maybe if I had implemented this on another day, I would have picked a list too; probably not.

What's more important though, is that needlessly *changing* this, would break it for everyone who has already customized this variable.

> At first I pasted changes from Emacs to Github but PR default message said not to use github, so I switched to Magit. I have created a local branch and I do not know what to do next.
> 
> I want to learn so I ask you @tarsius for help .

I am sorry, but I don't have the time to help you with that.

**Comment by o0nd7ots** [comment]
> I disagree that this is objectively better. Maybe if I had implemented this on another day, I would have picked a list too; probably not.

Don't you think that a list is more readable?
Do you know which one is more effective? (I do not. A list to me just seems more `lisp`y)

> What's more important though, is that needlessly _changing_ this, would break it for everyone who has already customized this variable.

Good point, I did not think about that.
Do you think that allowing users to choose between list and a string with regexp would be something that is worth implementing?

> I am sorry, but I don't have the time to help you with that.

Okay, no problem.

**Comment by tarsius** [comment]
> Don't you think that a list is more readable?
> Do you know which one is more effective? (I do not. A list to me just seems more `lisp`y)

For a list of characters I find a string quite suitable. And yes, it's actually a regexp, so `\\.` has to be used instead of `.`, but I don't think that's a big deal. When it comes to regexps, I think it is more appropriate to use strings, than to be "lispy".

> > What's more important though, is that needlessly _changing_ this, would break it for everyone who has already customized this variable.
> 
> Good point, I did not think about that. Do you think that allowing users to choose between list and a string with regexp would be something that is worth implementing?

No, I think that would needlessly make the code more complicated.

Even if you continue to prefer using a list here, being forced to use a string instead, isn't all that bad.

**Comment by o0nd7ots** [comment]
> For a list of characters I find a string quite suitable.

It's hard to argue with that :D

> I think it is more appropriate to use strings, than to be "lispy".

I know that "lispiness" is not a good benchmark.
I was just wondering if performance might be better for one of them.

> No, I think that would needlessly make the code more complicated.

That's what I thought. I am alright with that.

> Even if you continue to prefer using a list here, being forced to use a string instead, isn't all that bad.

I am more comfortable with lists than regexps so at least I get to learn something.


And responding to your first response, I think that I understand the problem.
Does it make impossible to include punctuation in words or is it just unhandy?

**Comment by tarsius** [comment]
> I was just wondering if performance might be better for one of them.

Performance isn't relevant here as `hl-todo--regexp` is only constructed once per buffer. Starting with a string is every so minimally more performant in this case.

> Does it make impossible to include punctuation in words or is it just unhandy?

I don't remember the details, but is a tradeoff. We can give up on matching on word boundaries and get quite a few false-positives and probably false-negatives. Or we can us word boundaries and it gets a bit awkward when it comes to punctuation. Needing `hl-todo-highlight-punctuation` and the code that deals with it, IMO is the better choice.

**Comment by o0nd7ots** [comment]
Okay, I see. Thanks for your response.

I would also like to ask of your use of `and` in code:
```
(and (not (equal hl-todo-highlight-punctuation ""))
                     (concat "[" hl-todo-highlight-punctuation "]"
                             (if hl-todo-require-punctuation "+" "*")))
```
Why `and` and not any variant of `if`?  
I think that `unless` would allow to remove `not` bracket.

**Comment by tarsius** [comment]
I use `and` and `or` when the return value matters. `when` and `unless` when we only care about side-effects. `if` may appear in either context, but only ever if there also is an `ELSE` part.
