### ISSUE TITLE
How do I get it to "work"?

### ISSUE THREAD

**Issue by mhavard999** [tarsius/hl-todo#8]
I have cloned this repo to `~/.emacs.d/lisp/hl-todo`on my machine.

I have this in my .emacs:
```elisp
(add-to-list 'load-path "~/.emacs.d/lisp/hl-todo")
(require 'hl-todo)
(hl-todo-mode 1)
```

But when I type `TODO` or `FIXME` it just looks normal:
![image](https://cloud.githubusercontent.com/assets/1484098/8530932/fb77c41c-23f1-11e5-872b-35c5a86fad8e.png)

I even did `M-x hl-todo-mode` a couple times, disabling and re-enabling it, to no avail.

The idea of this package is really cool and I would love to get it to work.

**Comment by tarsius** [comment]
There are two options: use a carrot or a stick. Or both!

**Comment by mhavard999** [comment]
Is it like not finished yet or something?
